name: aerospike-admin

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-admin:pyinstaller

build:
  - name: build
    script:
      - make
      - tar -C /work/source/build/bin -czf /work/source/build/bin/asadm.tgz asadm/
    artifact:
      - /work/source/build/bin/asadm.tgz
