name: aerospike-admin

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-admin:pyinstaller

build:
  - name: build
    script:
      - make
    artifact:
      - /work/source/build/bin/asadm
