codecov:
  bot: jdogmcsteezy

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
