#!/usr/bin/env bash
#
# docker/test.sh
#
# Smoke-test locally-built (or pullable) Aerospike asadm Docker images.
#
# Discovery: reads docker-bake.hcl to enumerate test image tags.
# Override:  test a specific image with -i IMAGE.
#
# Tests performed per image:
#   1. docker run --rm IMAGE --version  exits 0
#   2. Output contains the expected version string
#   3. (optional, -s) snyk container test
#

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

BAKE_FILE="docker-bake.hcl"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log_info() { printf '\e[36m[INFO]\e[0m    %s\n' "$*"; }
log_success() { printf '\e[32m[OK]\e[0m      %s\n' "$*"; }
log_warn() { printf '\e[33m[WARN]\e[0m    %s\n' "$*" >&2; }
log_failure() { printf '\e[31m[FAIL]\e[0m    %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------
function usage() {
  cat <<'EOF'
Usage: docker/test.sh -v VERSION [OPTIONS]
       docker/test.sh -i IMAGE -v VERSION [OPTIONS]

Smoke-test Aerospike asadm Docker images.

REQUIRED:
    -v, --version VERSION   Expected asadm version string, e.g. 5.0.0 or 5.0.0-rc1
                            Used to locate test image tags in docker-bake.hcl and to
                            verify the version printed by the container.

OPTIONS:
    -i, --image IMAGE   Test a specific image tag instead of auto-discovering from
                        docker-bake.hcl. IMAGE must be locally loaded or pullable.
    -d, --distro DISTRO Filter by distro; repeat for multiple (default: all in bake file)
                        Values: ubuntu24.04, ubi10
    -a, --arch ARCH     Filter by arch; repeat for multiple
                        Values: amd64, arm64
                        Default (no -i): host arch only
                        Default (with -i): host arch
    -s, --snyk          Run snyk container test after smoke tests pass.
                        Requires snyk CLI in PATH.
                        Results saved to snyk-<distro>-<arch>-<timestamp>.log
    -c, --clean         Remove each image with docker rmi after its tests pass.
    -h, --help          Show this help message

TESTS PERFORMED:
    1. docker run --rm --platform linux/<arch> IMAGE --version   exits 0
    2. Container output contains expected version string

PREREQUISITES:
    - Run docker/docker-build.sh -t first to build and load images locally.
    - docker-bake.hcl must exist in docker/ (generated by docker-build.sh).
    - For -i: the image must be accessible locally or via registry pull.

EXAMPLES:
    # Test all locally-built images (reads docker-bake.hcl, defaults to host arch)
    docker/test.sh -v 5.0.0-rc1

    # Test all arches for all distros
    docker/test.sh -v 5.0.0 -a amd64 -a arm64

    # Test a specific image tag
    docker/test.sh -i aerospike/aerospike-asadm:5.0.0-ubuntu24.04-amd64 -v 5.0.0

    # Test + Snyk scan + cleanup
    docker/test.sh -v 5.0.0 -s -c

    # Test only ubi10 on both arches
    docker/test.sh -v 5.0.0 -d ubi10 -a amd64 -a arm64
EOF
}

# ---------------------------------------------------------------------------
# get_bake_tag: extract the first image tag for a given distro+arch test
# target from docker-bake.hcl.
# ---------------------------------------------------------------------------
function get_bake_tag() {
  local distro="$1" arch="$2"
  local slug="${distro//\./-}"
  local target="${slug}-${arch}"
  awk "/^target \"${target}\" \{/,/^\}/" "${BAKE_FILE}" |
    grep -oE '"[^"]+/aerospike-asadm:[^"]+"' |
    head -1 |
    tr -d '"' ||
    true
}

# ---------------------------------------------------------------------------
# get_bake_test_entries: emit "distro arch tag" lines for all test targets
# found in docker-bake.hcl, filtered by DISTRO_FILTER and ARCH_FILTERS.
# ---------------------------------------------------------------------------
function get_bake_test_entries() {
  local distro_filter="$1"
  shift
  local arch_filters=("$@")

  if [[ ! -f "${BAKE_FILE}" ]]; then
    log_warn "${BAKE_FILE} not found. Run docker/docker-build.sh -t first."
    exit 1
  fi

  # slug → canonical distro name (must mirror what docker-build.sh produces)
  declare -A slug_to_distro=(
    ["ubuntu24-04"]="ubuntu24.04"
    ["ubi10"]="ubi10"
  )

  local test_line
  test_line=$(grep '^group "test"' "${BAKE_FILE}" || true)
  if [[ -z "${test_line}" ]]; then
    log_warn "No 'test' group found in ${BAKE_FILE}."
    return 0
  fi

  # Parse: group "test" { targets = ["t1", "t2", ...] }
  local targets_raw
  targets_raw=$(printf '%s' "${test_line}" |
    grep -oE '\[[^]]+\]' |
    tr -d '[]"' |
    tr ',' '\n' |
    tr -d ' ')

  while IFS= read -r target; do
    [[ -z "${target}" ]] && continue

    # target format: <distro-slug>-<arch>, e.g. ubuntu24-04-amd64, ubi10-arm64
    local arch="${target##*-}"
    local slug="${target%-"${arch}"}"
    local distro="${slug_to_distro[${slug}]:-${slug}}"

    # Apply distro filter
    [[ -n "${distro_filter}" && "${distro}" != "${distro_filter}" ]] && continue

    # Apply arch filter (empty = no filter)
    if [[ ${#arch_filters[@]} -gt 0 ]]; then
      local arch_match=false
      for af in "${arch_filters[@]}"; do
        [[ "${arch}" == "${af}" ]] && {
          arch_match=true
          break
        }
      done
      [[ "${arch_match}" == false ]] && continue
    fi

    local tag
    tag=$(get_bake_tag "${distro}" "${arch}")
    if [[ -z "${tag}" ]]; then
      log_warn "No tag found for target '${target}' in ${BAKE_FILE}"
      continue
    fi

    printf '%s %s %s\n' "${distro}" "${arch}" "${tag}"
  done <<<"${targets_raw}"
}

# ---------------------------------------------------------------------------
# test_image: run smoke tests against one image.
# Returns 0 on success, 1 on failure.
# ---------------------------------------------------------------------------
function test_image() {
  local image="$1" arch="$2" expected_version="$3" distro="${4:-}"

  log_info "====== Testing ======"
  log_info "  Image:    ${image}"
  log_info "  Distro:   ${distro:-n/a}"
  log_info "  Arch:     ${arch}"
  log_info "  Version:  ${expected_version}"
  echo ""

  # Ensure image is available
  if ! docker image inspect "${image}" >/dev/null 2>&1; then
    log_warn "Image not found locally: ${image}"
    log_info "Attempting pull..."
    if ! docker pull --platform "linux/${arch}" "${image}"; then
      log_failure "Could not find or pull image: ${image}"
      return 1
    fi
  fi

  # Smoke test: run asadm --version
  log_info "Running: docker run --rm --platform linux/${arch} ${image} --version"
  local output
  if ! output=$(docker run --rm --platform "linux/${arch}" "${image}" --version 2>&1); then
    log_failure "docker run exited non-zero."
    printf '%s\n' "${output}"
    return 1
  fi
  log_success "Container exited 0"

  # Verify version string in output (strip pre-release suffix for partial match)
  if [[ -n "${expected_version}" ]]; then
    local base_version
    base_version=$(printf '%s' "${expected_version}" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')
    if printf '%s' "${output}" | grep -qF "${base_version}"; then
      log_success "Version ${expected_version} confirmed in output"
    else
      log_warn "Expected version ${expected_version} not found in output:"
      printf '%s\n' "${output}"
    fi
  fi

  echo ""
  return 0
}

# ---------------------------------------------------------------------------
# run_snyk: optional non-fatal Snyk container scan.
# ---------------------------------------------------------------------------
function run_snyk() {
  local image="$1" arch="$2" distro="${3:-}"

  if ! command -v snyk >/dev/null 2>&1; then
    log_warn "snyk not found in PATH — skipping scan."
    return 0
  fi

  local ts
  ts=$(date -u +%Y%m%d%H%M%S)
  local scan_log="snyk-${distro:+${distro}-}${arch}-${ts}.log"

  local snyk_cmd=(snyk container test "${image}" "--platform=linux/${arch}")
  # Provide Dockerfile for more accurate results if available
  [[ -n "${distro}" && -f "${distro}/Dockerfile" ]] && snyk_cmd+=("--file=${distro}/Dockerfile")

  log_info "Running Snyk scan → ${scan_log}"
  # Non-fatal: findings are informational
  "${snyk_cmd[@]}" | tee "${scan_log}" || true

  local critical high
  critical=$(grep -c 'Critical severity' "${scan_log}" 2>/dev/null || true)
  high=$(grep -c 'High severity' "${scan_log}" 2>/dev/null || true)
  printf '\e[36m[INFO]\e[0m    Snyk: \e[91mCritical: %s\e[0m  \e[33mHigh: %s\e[0m  Log: %s\n' \
    "${critical:-0}" "${high:-0}" "${scan_log}"
  echo ""
}

# ---------------------------------------------------------------------------
# host_arch: return amd64 or arm64 based on uname -m
# ---------------------------------------------------------------------------
function host_arch() {
  local m
  m=$(uname -m)
  case "${m}" in
  x86_64) echo "amd64" ;;
  arm64 | aarch64) echo "arm64" ;;
  *) echo "${m}" ;;
  esac
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function main() {
  local VERSION=""
  local specific_image=""
  local distro_filter=""
  local arch_filters=()
  local snyk=false
  local clean=false

  while [[ $# -gt 0 ]]; do
    case "$1" in
    -v | --version)
      VERSION="$2"
      shift 2
      ;;
    -i | --image)
      specific_image="$2"
      shift 2
      ;;
    -d | --distro)
      distro_filter="$2"
      shift 2
      ;;
    -a | --arch)
      arch_filters+=("$2")
      shift 2
      ;;
    -s | --snyk)
      snyk=true
      shift
      ;;
    -c | --clean)
      clean=true
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      log_warn "Unknown option: $1"
      usage
      exit 1
      ;;
    esac
  done

  if [[ -z "${VERSION}" ]]; then
    log_warn "--version is required."
    usage
    exit 1
  fi

  local tested=0 failed=0

  _run_one() {
    local image="$1" arch="$2" distro="${3:-}"
    if test_image "${image}" "${arch}" "${VERSION}" "${distro}"; then
      [[ "${snyk}" == true ]] && run_snyk "${image}" "${arch}" "${distro}"
      if [[ "${clean}" == true ]]; then
        docker rmi -f "${image}" >/dev/null 2>&1 || true
        log_info "Removed image: ${image}"
      fi
      tested=$((tested + 1))
    else
      failed=$((failed + 1))
    fi
  }

  if [[ -n "${specific_image}" ]]; then
    # ---- Test a specific image ----
    local arch
    if [[ ${#arch_filters[@]} -gt 0 ]]; then
      arch="${arch_filters[0]}"
    else
      arch=$(host_arch)
    fi
    _run_one "${specific_image}" "${arch}"

  else
    # ---- Discover images from docker-bake.hcl ----

    # Default arch: host only (matches server-docker convention)
    if [[ ${#arch_filters[@]} -eq 0 ]]; then
      arch_filters=("$(host_arch)")
    fi

    while IFS=" " read -r distro arch tag; do
      [[ -z "${tag}" ]] && continue
      _run_one "${tag}" "${arch}" "${distro}"
    done < <(get_bake_test_entries "${distro_filter}" "${arch_filters[@]}")
  fi

  echo ""
  if [[ "${failed}" -gt 0 ]]; then
    log_failure "Results: ${tested} passed, ${failed} failed."
    exit 1
  elif [[ "${tested}" -eq 0 ]]; then
    log_warn "No images tested. Build images first with docker/docker-build.sh -t"
    exit 1
  else
    log_success "====== All ${tested} test(s) passed ======"
  fi
}

main "$@"
