FROM ubuntu:22.04
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

RUN apt -y update
ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh
RUN source /tmp/install_deps.sh && install_deps_ubuntu22.04
ADD . /opt/asadmin
WORKDIR /opt/asadmin
ENTRYPOINT ["/opt/asadmin/.github/docker/entrypoint.sh"]
CMD ["-b"]
