FROM debian:trixie
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
RUN useradd -u 9001 -m build

RUN apt -y update

ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh

RUN source /tmp/install_deps.sh && install_deps_debian13

ADD --chown=build:build . /opt/asbench
WORKDIR /opt/asbench
USER build
ENTRYPOINT ["/opt/asbench/.github/docker/entrypoint.sh"]
CMD ["-b"]