FROM redhat/ubi8:8.10
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh
RUN source /tmp/install_deps.sh && install_deps_redhat-el8
ADD . /opt/asbench
WORKDIR /opt/asbench
ENTRYPOINT ["/opt/asbench/.github/docker/entrypoint.sh"]
CMD ["-b"]
