FROM ubuntu:20.04
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
ARG JF_USERNAME
ENV JF_USERNAME=${JF_USERNAME}
ARG JF_TOKEN
ENV JF_TOKEN=${JF_TOKEN}
ARG PKG_VERSION
ENV PKG_VERSION=${PKG_VERSION}

RUN apt -y update
ADD .github/docker/test/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/test/install_test_deps.sh /tmp/install_test_deps.sh
RUN source /tmp/install_test_deps.sh && install_test_deps_ubuntu20.04
RUN apt -y install aerospike-asadm=$PKG_VERSION
ADD . /opt/asadm
WORKDIR /opt/asadm
ENTRYPOINT ["/opt/asadm/.github/docker/test/entrypoint.sh"]
CMD ["-t"]
