name: Black Formatting Check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true
    - name: Get Python version from Pipfile
      run: echo "PYTHON_VERSION=$(grep "python_version" Pipfile | cut -d ' ' -f 3  - | tr -d '"')" >> $GITHUB_ENV

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev --skip-lock

    - name: Run Black Check
      run: |
        pipenv run black --check . 