name: Black Formatting Check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get Python version from Pipfile
      id: get_python_version
      run: echo "python_version=$(grep 'python_version' Pipfile | cut -d '=" -f 2 | tr -d ' "')" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.get_python_version.outputs.python_version }}

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev --skip-lock

    - name: Run Black Check
      run: |
        pipenv run black --check . 