name: Mac Build CI

on:
  repository_dispatch:
    types: mac-build
  push:
    branches: [actionsHub, master, test-ready, TOOLS-1993-mac-build]
  pull_request:
    branches: [actionsHub]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Pipenv setup
        run: |
          brew update
          brew install pipenv
          pipenv check
      - name: Build asadm
        run: |
          make
      - name: Sanity Test tools
        run: |
          build/bin/asadm -e "info" 2>&1 | grep "Not able to connect"
          build/bin/asinfo -e "info" 2>&1 | grep "Not able to connect"
      - uses: actions/upload-artifact@v3
        with:
          name: asadm
          path: build/bin/asadm
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: asinfo
          path: build/bin/asinfo
          if-no-files-found: error
