name: Mac Build CI

on:
  repository_dispatch:
    types: mac-build
  push:
    branches: [actionsHub, master, test-ready, TOOLS-1993-mac-build]
  pull_request:
    branches: [actionsHub]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Pipenv setup
        run: |
          brew install pipenv
          pipenv check
      - name: Cache asadm and asinfo
        uses: actions/cache@v3
        id: cache-asadm-asinfo
        env:
          cache-name: cache-asadm-asinfo
        with:
          path: |
            build/bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.py') }}-${{ hashFiles('**/*.json') }}
      - name: Build asadm
        if: steps.cache-asadm-asinfo.outputs.cache-hit != 'true'
        run: |
          make
      - name: Sanity Test tools
        run: |
          echo $(pwd)/build/bin >> $GITHUB_PATH
          build/bin/asadm -e "info" 2>&1 | grep "Not able to connect"
          mv build/bin/asadm asadm
          build/bin/asinfo 
          build/bin/asinfo 2>&1 | grep "Not able to connect"
          mv asadm build/bin/asadm 
      - uses: actions/upload-artifact@v3
        with:
          name: asadm
          path: build/bin/asadm
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: asinfo
          path: build/bin/asinfo
          if-no-files-found: error
