name: Tests
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["dependabot/**"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Install JFrog CLI
        id: jf
        uses: step-security/setup-jfrog-cli@53aeacb709fce45d0baf69a13ec3342f7e2d71a9 # v5.1.0
        env:
          JF_URL: https://artifact.aerospike.io
          JF_PROJECT: database
        with:
          version: 2.78.8
          oidc-provider-name: database-gh-aerospike
          oidc-audience: database-gh-aerospike
      - name: Docker login to Artifactory
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: artifact.aerospike.io
          username: ${{ steps.jf.outputs.oidc-user }}
          password: ${{ steps.jf.outputs.oidc-token }}
      - name: Get Python version from Pipfile
        run: echo "PYTHON_VERSION=$(grep "python_version" Pipfile | cut -d ' ' -f 3  - | tr -d '"')" >> $GITHUB_ENV
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install pipenv==2026.8.0
          pipenv install --dev
      - name: Build
        run: |
          make
      - name: Tests with coverage report
        env:
          FEATKEY: ${{ secrets.TEST_FEAT_KEY }}
        run: |
          pipenv run bash -c "make coverage"
          pipenv run bash -c "coverage xml"
          pipenv run bash -c "coverage report --format=markdown" >> $GITHUB_STEP_SUMMARY
      - name: Upload Collectinfo for Debugging
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test_collectinfo
          path: /tmp/asadm_test*
          if-no-files-found: error
      - name: Upload Health Struct for Debugging
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: health_files
          path: "*_health_input.txt"
          if-no-files-found: error
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
