name: Unit Test
on:
  push:
    branches: [actionsHub, master, test-ready, "bugfix-*"]
  pull_request:
    branches: [test-ready, master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Python version from Pipfile
        run: echo "PYTHON_VERSION=$(grep "python_full_version" Pipfile | cut -d ' ' -f 3  - | tr -d '"')" >> $GITHUB_ENV
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Test with unittest
        run: |
          pipenv run bash -c "coverage run -m pytest test/unit"
          pipenv run bash -c "coverage xml"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          files: coverage.xml
          fail_ci_if_error: false
