name: Unit Test
on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Python version from Pipfile
      run: echo "PYTHON_VERSION=$(grep "python_version" Pipfile | cut -d ' ' -f 3  - | tr -d '"')" >> $GITHUB_ENV
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install --dev
    - name: Test with unittest2
      run: |
        pipenv run bash -c "coverage run -m pytest test/unit"
        pipenv run bash -c "coverage xml"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        files: coverage.xml
        fail_ci_if_error: false